import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { z } from "zod";
import { ArrowLeft, ArrowRight, Check, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Page, ProgressBar, Surface } from "@/components/app-ui";
import { questions } from "@/data/mock-data";
import { cn } from "@/lib/utils";

const searchSchema = z.object({ source: z.string().optional().default("practice"), material: z.string().optional().default("tiu-4") });
export const Route = createFileRoute("/question")({ validateSearch: (search) => searchSchema.parse(search), head: () => ({ meta: [{ title: "Practice — FastLearner" }, { name: "description", content: "Answer focused questions and learn from clear explanations." }, { property: "og:title", content: "Practice — FastLearner" }, { property: "og:description", content: "Answer focused questions and learn from clear explanations." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: QuestionPage });
function QuestionPage() {
  const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [done, setDone] = useState(false); const [score, setScore] = useState(0);
  const question = questions[index]; if (!question) return null;
  const answer = (choice: number) => { if (selected !== null) return; setSelected(choice); if (choice === question.answer) setScore((v) => v + 1); };
  const next = () => { if (index === questions.length - 1) setDone(true); else { setIndex((v) => v + 1); setSelected(null); } };
  if (done) return <Page narrow><div className="flex min-h-[70vh] items-center justify-center"><Surface className="w-full text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-success-soft text-success"><Check className="h-7 w-7" /></div><h1 className="mt-6 font-display text-3xl font-bold">Drill complete</h1><p className="mt-2 text-muted-foreground">You answered {score} of {questions.length} questions correctly.</p><div className="mt-7 flex justify-center gap-3"><Button variant="outline" asChild><Link to="/progress">View Progress</Link></Button><Button asChild><Link to="/">Back Home</Link></Button></div></Surface></div></Page>;
  const correct = selected === question.answer;
  return <Page narrow><div className="mb-8 flex items-center justify-between"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground"><ArrowLeft className="h-4 w-4" /> Exit</Link><span className="text-sm font-semibold text-muted-foreground">Question {String(index + 1).padStart(2, "0")} / {String(questions.length).padStart(2, "0")}</span></div><ProgressBar value={((index + 1) / questions.length) * 100} /><div className="mt-10"><p className="text-sm font-semibold text-primary">TIU · Numerik Berhitung</p><h1 className="mt-4 font-display text-2xl font-bold leading-relaxed md:text-3xl">{question.prompt}</h1><div className="mt-8 space-y-3">{question.options.map((option, choice) => { const isCorrect = choice === question.answer; const chosen = choice === selected; return <button key={option} type="button" onClick={() => answer(choice)} className={cn("flex w-full items-center gap-4 rounded-2xl border bg-card p-4 text-left transition-all", selected === null && "border-border hover:-translate-y-0.5 hover:border-primary hover:shadow-soft", selected !== null && isCorrect && "border-success bg-success-soft", selected !== null && chosen && !isCorrect && "border-destructive bg-danger-soft", selected !== null && !chosen && !isCorrect && "border-border opacity-55")}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-border bg-background font-semibold">{String.fromCharCode(65 + choice)}</span><span className="font-medium">{option}</span>{selected !== null && isCorrect && <Check className="ml-auto h-5 w-5 text-success" />}{selected !== null && chosen && !isCorrect && <X className="ml-auto h-5 w-5 text-destructive" />}</button>; })}</div>{selected !== null && <Surface className="mt-6 animate-rise"><div className={cn("flex items-center gap-2 font-display text-lg font-bold", correct ? "text-success" : "text-destructive")}>{correct ? <><Check /> Correct</> : <><X /> Incorrect · Correct answer: {String.fromCharCode(65 + question.answer)}</>}</div><h2 className="mt-5 font-display font-bold">Explanation</h2><p className="mt-2 leading-relaxed text-muted-foreground">{question.explanation}</p><Button className="mt-6 w-full" size="lg" onClick={next}>{index === questions.length - 1 ? "Finish Drill" : "Next Question"}<ArrowRight /></Button></Surface>}</div></Page>;
}